### PR TITLE
fix: update to use GITHUB_OUTPUT

### LINKED ISSUE #118: GitHub Actions: Deprecating save-state and set-output commands
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

### PR DESCRIPTION
**Pull request by tryvin**
GitHub now requires us to send output to the `GITHUB_OUTPUT` variable instead of the `::set-output` commands.

### CODE REVIEW

File: preflight.sh [hunk 1]
```diff
@@ -31,4 +31,4 @@ else
   fi
 fi
 echo "::debug ::Set PREFLIGHT_SHORT_LENGTH=$PREFLIGHT_SHORT_LENGTH"
-echo "::set-output name=PREFLIGHT_SHORT_LENGTH::$PREFLIGHT_SHORT_LENGTH"
+echo "PREFLIGHT_SHORT_LENGTH$PREFLIGHT_SHORT_LENGTH" >> $GITHUB_OUTPUT
```
Comment (rlespinasse) [inline preflight.sh]: Missing the `=` symbol

```suggestion
echo "PREFLIGHT_SHORT_LENGTH=$PREFLIGHT_SHORT_LENGTH" >> "$GITHUB_OUTPUT"
```

Comment (tryvin) [reply preflight.sh]: @rlespinasse Updated!

File: preflight.sh [hunk 2]
```diff
@@ -31,4 +31,4 @@ else
   fi
 fi
 echo "::debug ::Set PREFLIGHT_SHORT_LENGTH=$PREFLIGHT_SHORT_LENGTH"
-echo "PREFLIGHT_SHORT_LENGTH$PREFLIGHT_SHORT_LENGTH" >> $GITHUB_OUTPUT
+echo "PREFLIGHT_SHORT_LENGTH=$PREFLIGHT_SHORT_LENGTH" >> $GITHUB_OUTPUT
```
Comment (rlespinasse) [inline preflight.sh]: to avoid https://www.shellcheck.net/wiki/SC2086

```suggestion
echo "PREFLIGHT_SHORT_LENGTH=$PREFLIGHT_SHORT_LENGTH" >> "$GITHUB_OUTPUT"
```

**Comment by rlespinasse** [comment]
@tryvin the `action.yml` file also uses `set-output` commands, can you amend your PR to migrate this part to GITHUB_OUTPUT?

**Comment by tryvin** [comment]
@rlespinasse Done!

**Review by rlespinasse — APPROVED** [review]

**Comment by rlespinasse** [comment]
@tryvin Thank you for your contribution
